#
# Module manifest for module 'Az.Network'
#
# Generated by: Microsoft Corporation
#
# Generated on: 01/12/2022
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Az.Network.psm1'

# Version number of this module.
ModuleVersion = '5.2.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'f554cfcd-9cbb-4021-b158-fe20f0497f82'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Azure PowerShell - Networking service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.

For more information on Networking, please visit the following: https://docs.microsoft.com/azure/networking/networking-overview'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = 'Microsoft.Azure.PowerShell.AutoMapper.dll', 
               'Microsoft.Azure.Management.Network.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'Network.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = 'Add-AzApplicationGatewayAuthenticationCertificate', 
               'Get-AzApplicationGatewayAuthenticationCertificate', 
               'New-AzApplicationGatewayAuthenticationCertificate', 
               'Remove-AzApplicationGatewayAuthenticationCertificate', 
               'Set-AzApplicationGatewayAuthenticationCertificate', 
               'Get-AzApplicationGatewayAutoscaleConfiguration', 
               'New-AzApplicationGatewayAutoscaleConfiguration', 
               'Remove-AzApplicationGatewayAutoscaleConfiguration', 
               'Set-AzApplicationGatewayAutoscaleConfiguration', 
               'Get-AzApplicationGatewayAvailableWafRuleSet', 
               'Get-AzApplicationGatewayWafDynamicManifest', 
               'Get-AzApplicationGatewayAvailableSslOption', 
               'Add-AzApplicationGatewayBackendAddressPool', 
               'Get-AzApplicationGatewayBackendAddressPool', 
               'New-AzApplicationGatewayBackendAddressPool', 
               'Remove-AzApplicationGatewayBackendAddressPool', 
               'Set-AzApplicationGatewayBackendAddressPool', 
               'Add-AzApplicationGatewayBackendHttpSetting', 
               'Get-AzApplicationGatewayBackendHttpSetting', 
               'New-AzApplicationGatewayBackendHttpSetting', 
               'Remove-AzApplicationGatewayBackendHttpSetting', 
               'Set-AzApplicationGatewayBackendHttpSetting', 
               'Get-AzApplicationGatewayConnectionDraining', 
               'New-AzApplicationGatewayConnectionDraining', 
               'Remove-AzApplicationGatewayConnectionDraining', 
               'Set-AzApplicationGatewayConnectionDraining', 
               'Get-AzApplicationGatewayWebApplicationFirewallConfiguration', 
               'New-AzApplicationGatewayWebApplicationFirewallConfiguration', 
               'Set-AzApplicationGatewayWebApplicationFirewallConfiguration', 
               'New-AzApplicationGatewayFirewallDisabledRuleGroupConfig', 
               'New-AzApplicationGatewayFirewallExclusionConfig', 
               'New-AzApplicationGatewayFirewallPolicyExclusionManagedRule', 
               'New-AzApplicationGatewayFirewallPolicyExclusionManagedRuleGroup', 
               'New-AzApplicationGatewayFirewallPolicyExclusionManagedRuleSet', 
               'New-AzApplicationGatewayFirewallCondition', 
               'New-AzApplicationGatewayFirewallCustomRule', 
               'New-AzApplicationGatewayFirewallMatchVariable', 
               'New-AzApplicationGatewayFirewallPolicy', 
               'Get-AzApplicationGatewayFirewallPolicy', 
               'Remove-AzApplicationGatewayFirewallPolicy', 
               'Set-AzApplicationGatewayFirewallPolicy', 
               'New-AzApplicationGatewayFirewallPolicyExclusion', 
               'New-AzApplicationGatewayFirewallPolicyManagedRule', 
               'New-AzApplicationGatewayFirewallPolicyManagedRuleOverride', 
               'New-AzApplicationGatewayFirewallPolicyManagedRuleGroupOverride', 
               'New-AzApplicationGatewayFirewallPolicyManagedRuleSet', 
               'New-AzApplicationGatewayFirewallPolicySetting', 
               'Add-AzApplicationGatewayFrontendIPConfig', 
               'Get-AzApplicationGatewayFrontendIPConfig', 
               'New-AzApplicationGatewayFrontendIPConfig', 
               'Remove-AzApplicationGatewayFrontendIPConfig', 
               'Set-AzApplicationGatewayFrontendIPConfig', 
               'Add-AzApplicationGatewayFrontendPort', 
               'Get-AzApplicationGatewayFrontendPort', 
               'New-AzApplicationGatewayFrontendPort', 
               'Remove-AzApplicationGatewayFrontendPort', 
               'Set-AzApplicationGatewayFrontendPort', 
               'Get-AzApplicationGatewayIdentity', 
               'New-AzApplicationGatewayIdentity', 
               'Remove-AzApplicationGatewayIdentity', 
               'Set-AzApplicationGatewayIdentity', 
               'Add-AzApplicationGatewayIPConfiguration', 
               'Get-AzApplicationGatewayIPConfiguration', 
               'New-AzApplicationGatewayIPConfiguration', 
               'Remove-AzApplicationGatewayIPConfiguration', 
               'Set-AzApplicationGatewayIPConfiguration', 
               'Get-AzApplicationGatewayBackendHealth', 'Get-AzApplicationGateway', 
               'Add-AzApplicationGatewayHttpListener', 
               'Get-AzApplicationGatewayHttpListener', 
               'New-AzApplicationGatewayHttpListener', 
               'Remove-AzApplicationGatewayHttpListener', 
               'Set-AzApplicationGatewayHttpListener', 'New-AzApplicationGateway', 
               'Add-AzApplicationGatewaySslProfile', 
               'Get-AzApplicationGatewaySslProfile', 
               'New-AzApplicationGatewaySslProfile', 
               'Remove-AzApplicationGatewaySslProfile', 
               'Set-AzApplicationGatewaySslProfile', 
               'New-AzApplicationGatewayCustomError', 
               'Add-AzApplicationGatewayCustomError', 
               'Get-AzApplicationGatewayCustomError', 
               'Remove-AzApplicationGatewayCustomError', 
               'Set-AzApplicationGatewayCustomError', 
               'Add-AzApplicationGatewayHttpListenerCustomError', 
               'Get-AzApplicationGatewayHttpListenerCustomError', 
               'Remove-AzApplicationGatewayHttpListenerCustomError', 
               'Set-AzApplicationGatewayHttpListenerCustomError', 
               'New-AzApplicationGatewayPathRuleConfig', 
               'Add-AzApplicationGatewayProbeConfig', 
               'Get-AzApplicationGatewayProbeConfig', 
               'New-AzApplicationGatewayProbeConfig', 
               'Remove-AzApplicationGatewayProbeConfig', 
               'Set-AzApplicationGatewayProbeConfig', 
               'New-AzApplicationGatewayProbeHealthResponseMatch', 
               'Remove-AzApplicationGateway', 
               'Add-AzApplicationGatewayRequestRoutingRule', 
               'Get-AzApplicationGatewayRequestRoutingRule', 
               'New-AzApplicationGatewayRequestRoutingRule', 
               'Remove-AzApplicationGatewayRequestRoutingRule', 
               'Set-AzApplicationGatewayRequestRoutingRule', 
               'Add-AzApplicationGatewayRewriteRuleSet', 
               'Get-AzApplicationGatewayRewriteRuleSet', 
               'New-AzApplicationGatewayRewriteRuleSet', 
               'Remove-AzApplicationGatewayRewriteRuleSet', 
               'Set-AzApplicationGatewayRewriteRuleSet', 
               'New-AzApplicationGatewayRewriteRule', 
               'New-AzApplicationGatewayRewriteRuleActionSet', 
               'New-AzApplicationGatewayRewriteRuleHeaderConfiguration', 
               'New-AzApplicationGatewayRewriteRuleUrlConfiguration', 
               'Get-AzApplicationGatewayAvailableServerVariableAndHeader', 
               'New-AzApplicationGatewayRewriteRuleCondition', 
               'Add-AzApplicationGatewayRedirectConfiguration', 
               'Get-AzApplicationGatewayRedirectConfiguration', 
               'New-AzApplicationGatewayRedirectConfiguration', 
               'Remove-AzApplicationGatewayRedirectConfiguration', 
               'Set-AzApplicationGatewayRedirectConfiguration', 
               'Set-AzApplicationGateway', 'Get-AzApplicationGatewaySku', 
               'New-AzApplicationGatewaySku', 'Set-AzApplicationGatewaySku', 
               'Add-AzApplicationGatewaySslCertificate', 
               'Get-AzApplicationGatewaySslCertificate', 
               'New-AzApplicationGatewaySslCertificate', 
               'Remove-AzApplicationGatewaySslCertificate', 
               'Set-AzApplicationGatewaySslCertificate', 
               'Get-AzApplicationGatewaySslPolicy', 
               'New-AzApplicationGatewaySslPolicy', 
               'Remove-AzApplicationGatewaySslPolicy', 
               'Set-AzApplicationGatewaySslPolicy', 
               'Get-AzApplicationGatewaySslProfilePolicy', 
               'Remove-AzApplicationGatewaySslProfilePolicy', 
               'Set-AzApplicationGatewaySslProfilePolicy', 
               'Get-AzApplicationGatewayClientAuthConfiguration', 
               'New-AzApplicationGatewayClientAuthConfiguration', 
               'Remove-AzApplicationGatewayClientAuthConfiguration', 
               'Set-AzApplicationGatewayClientAuthConfiguration', 
               'Get-AzApplicationGatewaySslPredefinedPolicy', 
               'Start-AzApplicationGateway', 'Stop-AzApplicationGateway', 
               'Add-AzApplicationGatewayTrustedRootCertificate', 
               'Get-AzApplicationGatewayTrustedRootCertificate', 
               'New-AzApplicationGatewayTrustedRootCertificate', 
               'Remove-AzApplicationGatewayTrustedRootCertificate', 
               'Set-AzApplicationGatewayTrustedRootCertificate', 
               'Add-AzApplicationGatewayTrustedClientCertificate', 
               'Get-AzApplicationGatewayTrustedClientCertificate', 
               'New-AzApplicationGatewayTrustedClientCertificate', 
               'Remove-AzApplicationGatewayTrustedClientCertificate', 
               'Set-AzApplicationGatewayTrustedClientCertificate', 
               'Add-AzApplicationGatewayUrlPathMapConfig', 
               'Get-AzApplicationGatewayUrlPathMapConfig', 
               'New-AzApplicationGatewayUrlPathMapConfig', 
               'Remove-AzApplicationGatewayUrlPathMapConfig', 
               'Set-AzApplicationGatewayUrlPathMapConfig', 
               'New-AzApplicationGatewayPrivateLinkConfiguration', 
               'Add-AzApplicationGatewayPrivateLinkConfiguration', 
               'Set-AzApplicationGatewayPrivateLinkConfiguration', 
               'Get-AzApplicationGatewayPrivateLinkConfiguration', 
               'Remove-AzApplicationGatewayPrivateLinkConfiguration', 
               'New-AzApplicationGatewayPrivateLinkIpConfiguration', 
               'Add-AzExpressRouteCircuitAuthorization', 
               'Get-AzExpressRouteCircuitAuthorization', 
               'New-AzExpressRouteCircuitAuthorization', 
               'Remove-AzExpressRouteCircuitAuthorization', 
               'Move-AzExpressRouteCircuit', 'Get-AzExpressRouteCircuitARPTable', 
               'Get-AzExpressRouteCircuitRouteTable', 
               'Get-AzExpressRouteCircuitRouteTableSummary', 
               'Get-AzExpressRouteCircuitStat', 
               'Add-AzLoadBalancerInboundNatPoolConfig', 
               'Get-AzLoadBalancerInboundNatPoolConfig', 
               'New-AzLoadBalancerInboundNatPoolConfig', 
               'Remove-AzLoadBalancerInboundNatPoolConfig', 
               'Set-AzLoadBalancerInboundNatPoolConfig', 
               'Get-AzExpressRouteCircuit', 'New-AzExpressRouteCircuit', 
               'Add-AzExpressRouteCircuitPeeringConfig', 
               'Get-AzExpressRouteCircuitPeeringConfig', 
               'New-AzExpressRouteCircuitPeeringConfig', 
               'Remove-AzExpressRouteCircuitPeeringConfig', 
               'Set-AzExpressRouteCircuitPeeringConfig', 
               'Remove-AzExpressRouteCircuit', 'Set-AzExpressRouteCircuit', 
               'Get-AzExpressRoutePort', 'New-AzExpressRoutePort', 
               'Get-AzExpressRoutePortLinkConfig', 'Remove-AzExpressRoutePort', 
               'Set-AzExpressRoutePort', 'Get-AzExpressRoutePortsLocation', 
               'Get-AzExpressRoutePortIdentity', 'New-AzExpressRoutePortIdentity', 
               'Remove-AzExpressRoutePortIdentity', 
               'Set-AzExpressRoutePortIdentity', 
               'Add-AzExpressRoutePortAuthorization', 
               'Get-AzExpressRoutePortAuthorization', 
               'Remove-AzExpressRoutePortAuthorization', 
               'Get-AzEffectiveNetworkSecurityGroup', 'Get-AzEffectiveRouteTable', 
               'Add-AzNetworkInterfaceIpConfig', 'Get-AzNetworkInterfaceIpConfig', 
               'New-AzNetworkInterfaceIpConfig', 
               'Remove-AzNetworkInterfaceIpConfig', 
               'Set-AzNetworkInterfaceIpConfig', 'New-AzNetworkWatcher', 
               'Get-AzNetworkWatcher', 'Remove-AzNetworkWatcher', 
               'New-AzNetworkWatcherPacketCapture', 
               'New-AzNetworkWatcherPacketCaptureV2', 
               'Get-AzNetworkWatcherPacketCapture', 
               'Stop-AzNetworkWatcherPacketCapture', 
               'Remove-AzNetworkWatcherPacketCapture', 
               'New-AzPacketCaptureFilterConfig', 'New-AzPacketCaptureScopeConfig', 
               'Get-AzNetworkWatcherTopology', 
               'Get-AzNetworkWatcherSecurityGroupView', 
               'Test-AzNetworkWatcherIPFlow', 'Get-AzNetworkWatcherNextHop', 
               'Start-AzNetworkWatcherResourceTroubleshooting', 
               'Get-AzNetworkWatcherTroubleshootingResult', 
               'Get-AzNetworkWatcherFlowLogStatus', 
               'Set-AzNetworkWatcherConfigFlowLog', 'New-AzNetworkWatcherFlowLog', 
               'Set-AzNetworkWatcherFlowLog', 'Get-AzNetworkWatcherFlowLog', 
               'Remove-AzNetworkWatcherFlowLog', 
               'Test-AzNetworkWatcherConnectivity', 
               'Get-AzNetworkWatcherReachabilityReport', 
               'Get-AzNetworkWatcherReachabilityProvidersList', 
               'New-AzNetworkWatcherConnectionMonitorEndpointObject', 
               'New-AzNetworkWatcherConnectionMonitorObject', 
               'New-AzNetworkWatcherConnectionMonitorEndpointScopeItemObject', 
               'New-AzNetworkWatcherConnectionMonitorTestConfigurationObject', 
               'New-AzNetworkWatcherConnectionMonitorTestGroupObject', 
               'New-AzNetworkWatcherConnectionMonitorOutputObject', 
               'New-AzNetworkWatcherConnectionMonitorProtocolConfigurationObject', 
               'New-AzNetworkWatcherConnectionMonitor', 
               'Set-AzNetworkWatcherConnectionMonitor', 
               'Start-AzNetworkWatcherConnectionMonitor', 
               'Stop-AzNetworkWatcherConnectionMonitor', 
               'Remove-AzNetworkWatcherConnectionMonitor', 
               'Get-AzNetworkWatcherConnectionMonitor', 
               'Get-AzNetworkWatcherConnectionMonitorReport', 
               'Invoke-AzNetworkWatcherNetworkConfigurationDiagnostic', 
               'New-AzNetworkWatcherNetworkConfigurationDiagnosticProfile', 
               'Get-AzExpressRouteServiceProvider', 
               'Test-AzPrivateIPAddressAvailability', 'Get-AzPublicIpAddress', 
               'New-AzPublicIpAddress', 'Remove-AzPublicIpAddress', 
               'Set-AzPublicIpAddress', 'Get-AzPublicIpPrefix', 
               'New-AzPublicIpPrefix', 'Remove-AzPublicIpPrefix', 
               'Set-AzPublicIpPrefix', 'Get-AzRouteTable', 'New-AzRouteTable', 
               'Remove-AzRouteTable', 'Add-AzRouteConfig', 'Get-AzRouteConfig', 
               'New-AzRouteConfig', 'Remove-AzRouteConfig', 'Set-AzRouteConfig', 
               'Set-AzRouteTable', 'New-AzRadiusServer', 
               'Set-AzVirtualNetworkGateway', 'Get-AzVirtualNetworkGateway', 
               'New-AzVirtualNetworkGateway', 
               'Get-AzVirtualNetworkGatewayVpnclientConnectionHealth', 
               'Get-AzVpnClientRootCertificate', 
               'Get-AzVpnClientRevokedCertificate', 
               'Add-AzVpnClientRootCertificate', 
               'Add-AzVpnClientRevokedCertificate', 
               'New-AzVpnClientRootCertificate', 
               'New-AzVpnClientRevokedCertificate', 
               'Resize-AzVirtualNetworkGateway', 
               'Remove-AzVpnClientRevokedCertificate', 
               'Remove-AzVpnClientRootCertificate', 'Get-AzVpnClientPackage', 
               'New-AzVpnClientConfiguration', 'Get-AzVpnClientConfiguration', 
               'New-AzVirtualNetworkGatewayIpConfig', 
               'Add-AzVirtualNetworkGatewayIpConfig', 
               'Remove-AzVirtualNetworkGatewayIpConfig', 
               'Remove-AzVirtualNetworkGateway', 'Reset-AzVirtualNetworkGateway', 
               'Set-AzVirtualNetworkGatewayDefaultSite', 
               'Remove-AzVirtualNetworkGatewayDefaultSite', 
               'New-AzVpnClientIpsecPolicy', 'New-AzVpnClientIpsecParameter', 
               'Set-AzVpnClientIpsecParameter', 'Get-AzVpnClientIpsecParameter', 
               'Remove-AzVpnClientIpsecParameter', 'Remove-AzLocalNetworkGateway', 
               'Get-AzLocalNetworkGateway', 'New-AzLocalNetworkGateway', 
               'Set-AzLocalNetworkGateway', 
               'Get-AzVirtualNetworkGatewayConnection', 
               'Get-AzVirtualNetworkGatewayConnectionIkeSa', 
               'Reset-AzVirtualNetworkGatewayConnection', 
               'Get-AzVirtualNetworkGatewayConnectionSharedKey', 
               'New-AzVirtualNetworkGatewayConnection', 
               'Remove-AzVirtualNetworkGatewayConnection', 
               'Reset-AzVirtualNetworkGatewayConnectionSharedKey', 
               'Set-AzVirtualNetworkGatewayConnectionSharedKey', 
               'Set-AzVirtualNetworkGatewayConnection', 'New-AzIpsecPolicy', 
               'New-AzIpsecTrafficSelectorPolicy', 
               'Get-AzLoadBalancerBackendAddressPool', 
               'New-AzLoadBalancerBackendAddressPool', 
               'Remove-AzLoadBalancerBackendAddressPool', 
               'Set-AzLoadBalancerBackendAddressPool', 
               'New-AzLoadBalancerBackendAddressPoolTunnelInterfaceConfig', 
               'New-AzLoadBalancerBackendAddressConfig', 
               'Get-AzLoadBalancerBackendAddressPoolConfig', 
               'Add-AzLoadBalancerBackendAddressPoolConfig', 
               'New-AzLoadBalancerBackendAddressPoolConfig', 
               'Remove-AzLoadBalancerBackendAddressPoolConfig', 
               'Get-AzLoadBalancerBackendAddressInboundNatRulePortMapping', 
               'Set-AzLoadBalancerFrontendIpConfig', 
               'Get-AzLoadBalancerFrontendIpConfig', 
               'Add-AzLoadBalancerFrontendIpConfig', 
               'New-AzLoadBalancerFrontendIpConfig', 
               'Remove-AzLoadBalancerFrontendIpConfig', 'Get-AzLoadBalancer', 
               'Set-AzLoadBalancerInboundNatRuleConfig', 
               'Get-AzLoadBalancerInboundNatRuleConfig', 
               'Add-AzLoadBalancerInboundNatRuleConfig', 
               'New-AzLoadBalancerInboundNatRuleConfig', 
               'Remove-AzLoadBalancerInboundNatRuleConfig', 
               'Get-AzBgpServiceCommunity', 'Get-AzRouteFilter', 'Set-AzRouteFilter', 
               'Remove-AzRouteFilter', 'New-AzRouteFilter', 
               'Get-AzRouteFilterRuleConfig', 'Add-AzRouteFilterRuleConfig', 
               'Remove-AzRouteFilterRuleConfig', 'Set-AzRouteFilterRuleConfig', 
               'New-AzRouteFilterRuleConfig', 'Set-AzLoadBalancerRuleConfig', 
               'Get-AzLoadBalancerRuleConfig', 'Add-AzLoadBalancerRuleConfig', 
               'New-AzLoadBalancerRuleConfig', 'Remove-AzLoadBalancerRuleConfig', 
               'New-AzLoadBalancer', 'Set-AzLoadBalancerProbeConfig', 
               'Get-AzLoadBalancerProbeConfig', 'Add-AzLoadBalancerProbeConfig', 
               'New-AzLoadBalancerProbeConfig', 'Remove-AzLoadBalancerProbeConfig', 
               'Remove-AzLoadBalancer', 'Set-AzLoadBalancer', 
               'Add-AzLoadBalancerOutboundRuleConfig', 
               'Get-AzLoadBalancerOutboundRuleConfig', 
               'New-AzLoadBalancerOutboundRuleConfig', 
               'Set-AzLoadBalancerOutboundRuleConfig', 
               'Remove-AzLoadBalancerOutboundRuleConfig', 
               'Remove-AzNetworkInterface', 'Get-AzNetworkInterface', 
               'New-AzNetworkInterface', 'Set-AzNetworkInterface', 
               'Get-AzNetworkSecurityGroup', 'New-AzNetworkSecurityRuleConfig', 
               'Get-AzNetworkSecurityRuleConfig', 
               'Remove-AzNetworkSecurityRuleConfig', 
               'Set-AzNetworkSecurityRuleConfig', 
               'Add-AzNetworkSecurityRuleConfig', 'New-AzNetworkSecurityGroup', 
               'Remove-AzNetworkSecurityGroup', 'Set-AzNetworkSecurityGroup', 
               'Test-AzDnsAvailability', 'Add-AzVirtualNetworkPeering', 
               'Get-AzVirtualNetworkPeering', 'Remove-AzVirtualNetworkPeering', 
               'Set-AzVirtualNetworkPeering', 'Sync-AzVirtualNetworkPeering', 
               'Remove-AzVirtualNetwork', 'Set-AzVirtualNetwork', 
               'Remove-AzVirtualNetworkSubnetConfig', 
               'Set-AzVirtualNetworkSubnetConfig', 
               'Get-AzVirtualNetworkSubnetConfig', 
               'Add-AzVirtualNetworkSubnetConfig', 
               'New-AzVirtualNetworkSubnetConfig', 'New-AzDelegation', 
               'Add-AzDelegation', 'Get-AzDelegation', 'Remove-AzDelegation', 
               'Get-AzAvailableServiceDelegation', 'Get-AzVirtualNetwork', 
               'New-AzVirtualNetwork', 'Get-AzVirtualNetworkGatewayBgpPeerStatus', 
               'Get-AzVirtualNetworkGatewayAdvertisedRoute', 
               'Get-AzVirtualNetworkGatewayLearnedRoute', 'Get-AzNetworkUsage', 
               'Get-AzVirtualNetworkUsageList', 
               'Get-AzVirtualNetworkAvailableEndpointService', 
               'Get-AzVirtualNetworkGatewaySupportedVpnDevice', 
               'Get-AzVirtualNetworkGatewayConnectionVpnDeviceConfigScript', 
               'New-AzApplicationSecurityGroup', 
               'Remove-AzApplicationSecurityGroup', 
               'Get-AzApplicationSecurityGroup', 'New-AzPublicIpTag', 
               'New-AzDdosProtectionPlan', 'Get-AzDdosProtectionPlan', 
               'Remove-AzDdosProtectionPlan', 
               'New-AzNetworkWatcherProtocolConfiguration', 
               'Add-AzExpressRouteCircuitConnectionConfig', 
               'Set-AzExpressRouteCircuitConnectionConfig', 
               'Get-AzExpressRouteCircuitConnectionConfig', 
               'Remove-AzExpressRouteCircuitConnectionConfig', 
               'New-AzServiceEndpointPolicy', 'Remove-AzServiceEndpointPolicy', 
               'Get-AzServiceEndpointPolicy', 
               'New-AzServiceEndpointPolicyDefinition', 
               'Remove-AzServiceEndpointPolicyDefinition', 
               'Get-AzServiceEndpointPolicyDefinition', 
               'Set-AzServiceEndpointPolicyDefinition', 
               'Add-AzServiceEndpointPolicyDefinition', 
               'Set-AzServiceEndpointPolicy', 'New-AzVirtualWan', 
               'Update-AzVirtualWan', 'Get-AzVirtualWan', 'Remove-AzVirtualWan', 
               'Get-AzVirtualWanVpnServerConfiguration', 
               'Get-AzVirtualWanVpnServerConfigurationVpnProfile', 
               'New-AzVirtualHub', 'Get-AzVirtualHub', 'Update-AzVirtualHub', 
               'Remove-AzVirtualHub', 'Set-AzVirtualHub', 'New-AzVirtualHubRoute', 
               'Add-AzVirtualHubRoute', 'New-AzVirtualHubRouteTable', 
               'Add-AzVirtualHubRouteTable', 'Get-AzVirtualHubRouteTable', 
               'Remove-AzVirtualHubRouteTable', 'New-AzRoutingPolicy', 
               'Get-AzRoutingPolicy', 'Add-AzRoutingPolicy', 
               'Remove-AzRoutingPolicy', 'Set-AzRoutingPolicy', 
               'New-AzRoutingIntent', 'Get-AzRoutingIntent', 'Set-AzRoutingIntent', 
               'Remove-AzRoutingIntent', 'New-AzVpnGateway', 'Reset-AzVpnGateway', 
               'Get-AzVpnGateway', 'Update-AzVpnGateway', 'Remove-AzVpnGateway', 
               'Start-AzVpnGatewayPacketCapture', 'Stop-AzVpnGatewayPacketCapture', 
               'New-AzVpnGatewayNatRule', 'Update-AzVpnGatewayNatRule', 
               'Remove-AzVpnGatewayNatRule', 'Get-AzVpnGatewayNatRule', 
               'Start-AzVpnConnectionPacketCapture', 
               'Stop-AzVpnConnectionPacketCapture', 'New-AzVpnSite', 
               'New-AzVpnSiteLink', 'New-AzVpnSiteLinkConnection', 'Get-AzVpnSite', 
               'Reset-AzVpnSiteLinkConnection', 'Get-AzVpnSiteLinkConnectionIkeSa', 
               'Update-AzVpnSite', 'Remove-AzVpnSite', 'New-AzVpnConnection', 
               'Get-AzVpnConnection', 'Update-AzVpnConnection', 
               'Remove-AzVpnConnection', 'New-AzVirtualHubVnetConnection', 
               'Get-AzVirtualHubVnetConnection', 
               'Remove-AzVirtualHubVnetConnection', 
               'Update-AzVirtualHubVnetConnection', 'Get-AzVpnServerConfiguration', 
               'New-AzVpnServerConfiguration', 'Remove-AzVpnServerConfiguration', 
               'Update-AzVpnServerConfiguration', 
               'Get-AzVpnServerConfigurationPolicyGroup', 
               'New-AzVpnServerConfigurationPolicyGroup', 
               'Remove-AzVpnServerConfigurationPolicyGroup', 
               'Update-AzVpnServerConfigurationPolicyGroup', 'Get-AzP2sVpnGateway', 
               'Disconnect-AzP2sVpnGatewayVpnConnection', 
               'Get-AzP2sVpnGatewayConnectionHealth', 
               'Get-AzP2sVpnGatewayDetailedConnectionHealth', 
               'Get-AzP2sVpnGatewayVpnProfile', 'New-AzP2sVpnGateway', 
               'Remove-AzP2sVpnGateway', 'Update-AzP2sVpnGateway', 
               'Reset-AzP2sVpnGateway', 'Get-AzVirtualWanVpnConfiguration', 
               'Get-AzFirewall', 'Set-AzFirewall', 'New-AzFirewall', 
               'Remove-AzFirewall', 'New-AzFirewallApplicationRuleCollection', 
               'New-AzFirewallApplicationRule', 'New-AzFirewallNatRuleCollection', 
               'New-AzFirewallNatRule', 'New-AzFirewallNetworkRuleCollection', 
               'New-AzFirewallNetworkRule', 'New-AzFirewallThreatIntelWhitelist', 
               'New-AzFirewallHubPublicIpAddress', 'New-AzFirewallHubIpAddress', 
               'New-AzFirewallPublicIpAddress', 'Get-AzFirewallFqdnTag', 
               'Get-AzNetworkProfile', 'New-AzNetworkProfile', 
               'Remove-AzNetworkProfile', 'Set-AzNetworkProfile', 
               'New-AzContainerNicConfig', 'New-AzContainerNicConfigIpConfig', 
               'Add-AzNetworkInterfaceTapConfig', 
               'Get-AzNetworkInterfaceTapConfig', 
               'Set-AzNetworkInterfaceTapConfig', 
               'Remove-AzNetworkInterfaceTapConfig', 'Get-AzVirtualNetworkTap', 
               'New-AzVirtualNetworkTap', 'Remove-AzVirtualNetworkTap', 
               'Set-AzVirtualNetworkTap', 'Get-AzExpressRouteGateway', 
               'New-AzExpressRouteGateway', 'Remove-AzExpressRouteGateway', 
               'Set-AzExpressRouteGateway', 'Get-AzExpressRouteConnection', 
               'New-AzExpressRouteConnection', 'Remove-AzExpressRouteConnection', 
               'Set-AzExpressRouteConnection', 'Get-AzExpressRouteCrossConnection', 
               'Set-AzExpressRouteCrossConnection', 
               'Add-AzExpressRouteCrossConnectionPeering', 
               'Get-AzExpressRouteCrossConnectionPeering', 
               'Remove-AzExpressRouteCrossConnectionPeering', 
               'Get-AzExpressRouteCrossConnectionArpTable', 
               'Get-AzExpressRouteCrossConnectionRouteTable', 
               'Get-AzExpressRouteCrossConnectionRouteTableSummary', 
               'Get-AzNatGateway', 'New-AzNatGateway', 'Remove-AzNatGateway', 
               'Set-AzNatGateway', 'Get-AzNetworkServiceTag', 
               'New-AzPrivateEndpoint', 'Get-AzPrivateEndpoint', 
               'Remove-AzPrivateEndpoint', 'New-AzPrivateLinkServiceConnection', 
               'New-AzPrivateDnsZoneConfig', 'Remove-AzPrivateDnsZoneGroup', 
               'Get-AzPrivateDnsZoneGroup', 'New-AzPrivateDnsZoneGroup', 
               'Set-AzPrivateDnsZoneGroup', 'New-AzPrivateLinkService', 
               'Get-AzPrivateLinkService', 'Remove-AzPrivateLinkService', 
               'New-AzPrivateLinkServiceIpConfig', 'Set-AzPrivateEndpoint', 
               'Set-AzPrivateLinkService', 'Set-AzPrivateEndpointConnection', 
               'Get-AzPrivateEndpointConnection', 
               'Remove-AzPrivateEndpointConnection', 
               'Get-AzAutoApprovedPrivateLinkService', 
               'Test-AzPrivateLinkServiceVisibility', 
               'Approve-AzPrivateEndpointConnection', 
               'Deny-AzPrivateEndpointConnection', 
               'Get-AzAvailablePrivateEndpointType', 'Get-AzAvailableServiceAlias', 
               'Get-AzPrivateLinkResource', 'New-AzBastion', 'Get-AzBastion', 
               'Remove-AzBastion', 'Set-AzBastion', 
               'Start-AzVirtualNetworkGatewayPacketCapture', 
               'Stop-AzVirtualNetworkGatewayPacketCapture', 
               'Start-AzVirtualNetworkGatewayConnectionPacketCapture', 
               'Stop-AzVirtualNetworkGatewayConnectionPacketCapture', 
               'Disconnect-AzVirtualNetworkGatewayVpnConnection', 
               'New-AzFirewallPolicyNetworkRule', 'New-AzFirewallPolicyNatRule', 
               'New-AzFirewallPolicyApplicationRule', 
               'New-AzFirewallPolicyNatRuleCollection', 
               'New-AzFirewallPolicyFilterRuleCollection', 
               'New-AzFirewallPolicyRuleCollectionGroup', 
               'Set-AzFirewallPolicyRuleCollectionGroup', 
               'Get-AzFirewallPolicyRuleCollectionGroup', 
               'Remove-AzFirewallPolicyRuleCollectionGroup', 
               'New-AzFirewallPolicy', 'Get-AzFirewallPolicy', 
               'Set-AzFirewallPolicy', 'Remove-AzFirewallPolicy', 
               'New-AzFirewallPolicyIntrusionDetection', 
               'New-AzFirewallPolicyIntrusionDetectionBypassTraffic', 
               'New-AzFirewallPolicyIntrusionDetectionSignatureOverride', 
               'New-AzFirewallPolicyThreatIntelWhitelist', 
               'New-AzFirewallPolicyDnsSetting', 'New-AzFirewallPolicySqlSetting', 
               'New-AzFirewallPolicyExplicitProxy', 'New-AzVirtualRouter', 
               'Remove-AzVirtualRouter', 'Get-AzVirtualRouter', 
               'Update-AzVirtualRouter', 'Add-AzVirtualRouterPeer', 
               'Update-AzVirtualRouterPeer', 'Remove-AzVirtualRouterPeer', 
               'Get-AzVirtualRouterPeer', 'Get-AzVirtualRouterPeerAdvertisedRoute', 
               'Get-AzVirtualRouterPeerLearnedRoute', 'New-AzRouteServer', 
               'Remove-AzRouteServer', 'Get-AzRouteServer', 'Update-AzRouteServer', 
               'Add-AzRouteServerPeer', 'Update-AzRouteServerPeer', 
               'Remove-AzRouteServerPeer', 'Get-AzRouteServerPeer', 
               'Get-AzRouteServerPeerAdvertisedRoute', 
               'Get-AzRouteServerPeerLearnedRoute', 'New-AzIpGroup', 
               'Remove-AzIpGroup', 'Get-AzIpGroup', 'Set-AzIpGroup', 
               'New-AzIpConfigurationBgpPeeringAddressObject', 
               'New-AzIpAllocation', 'Get-AzIpAllocation', 'Remove-AzIpAllocation', 
               'Set-AzIpAllocation', 'New-AzSecurityPartnerProvider', 
               'Remove-AzSecurityPartnerProvider', 'Get-AzSecurityPartnerProvider', 
               'Set-AzSecurityPartnerProvider', 'Reset-AzHubRouter', 
               'New-AzVHubRoute', 'New-AzStaticRoute', 'New-AzRoutingConfiguration', 
               'New-AzVHubRouteTable', 'Get-AzVHubRouteTable', 
               'Update-AzVHubRouteTable', 'Remove-AzVHubRouteTable', 
               'Get-AzNetworkVirtualAppliance', 'New-AzNetworkVirtualAppliance', 
               'Remove-AzNetworkVirtualAppliance', 
               'Update-AzNetworkVirtualAppliance', 'Get-AzVirtualApplianceSite', 
               'New-AzVirtualApplianceSite', 'Remove-AzVirtualApplianceSite', 
               'Update-AzVirtualApplianceSite', 'New-AzOffice365PolicyProperty', 
               'Get-AzNetworkVirtualApplianceSku', 
               'New-AzVirtualApplianceSkuProperty', 'New-AzCustomIpPrefix', 
               'Update-AzCustomIpPrefix', 'Get-AzCustomIpPrefix', 
               'Remove-AzCustomIpPrefix', 'New-AzExpressRoutePortLOA', 
               'New-AzO365PolicyProperty', 'Get-AzVirtualNetworkGatewayNatRule', 
               'New-AzVirtualNetworkGatewayNatRule', 
               'Update-AzVirtualNetworkGatewayNatRule', 
               'Remove-AzVirtualNetworkGatewayNatRule', 
               'New-AzVirtualNetworkGatewayPolicyGroup', 
               'New-AzVirtualNetworkGatewayPolicyGroupMember', 
               'New-AzVpnClientConnectionConfiguration', 
               'Get-AzVirtualHubBgpConnection', 'New-AzVirtualHubBgpConnection', 
               'Remove-AzVirtualHubBgpConnection', 
               'Update-AzVirtualHubBgpConnection', 
               'New-AzPrivateEndpointIpConfiguration', 
               'Get-AzApplicationGatewayListener', 
               'New-AzApplicationGatewayListener', 
               'Add-AzApplicationGatewayListener', 
               'Set-AzApplicationGatewayListener', 
               'Remove-AzApplicationGatewayListener', 
               'Get-AzApplicationGatewayBackendSetting', 
               'New-AzApplicationGatewayBackendSetting', 
               'Add-AzApplicationGatewayBackendSetting', 
               'Set-AzApplicationGatewayBackendSetting', 
               'Remove-AzApplicationGatewayBackendSetting', 
               'Get-AzApplicationGatewayRoutingRule', 
               'New-AzApplicationGatewayRoutingRule', 
               'Add-AzApplicationGatewayRoutingRule', 
               'Set-AzApplicationGatewayRoutingRule', 
               'Remove-AzApplicationGatewayRoutingRule', 'Get-AzNetworkManager', 
               'New-AzNetworkManager', 'Remove-AzNetworkManager', 
               'Set-AzNetworkManager', 'Get-AzNetworkManagerGroup', 
               'New-AzNetworkManagerGroup', 'Remove-AzNetworkManagerGroup', 
               'Set-AzNetworkManagerGroup', 
               'Get-AzNetworkManagerConnectivityConfiguration', 
               'New-AzNetworkManagerConnectivityConfiguration', 
               'Remove-AzNetworkManagerConnectivityConfiguration', 
               'Set-AzNetworkManagerConnectivityConfiguration', 
               'Get-AzNetworkManagerSecurityAdminConfiguration', 
               'New-AzNetworkManagerSecurityAdminConfiguration', 
               'Remove-AzNetworkManagerSecurityAdminConfiguration', 
               'Set-AzNetworkManagerSecurityAdminConfiguration', 
               'Get-AzNetworkManagerSecurityAdminRuleCollection', 
               'New-AzNetworkManagerSecurityAdminRuleCollection', 
               'Remove-AzNetworkManagerSecurityAdminRuleCollection', 
               'Set-AzNetworkManagerSecurityAdminRuleCollection', 
               'Get-AzNetworkManagerSecurityAdminRule', 
               'New-AzNetworkManagerSecurityAdminRule', 
               'Remove-AzNetworkManagerSecurityAdminRule', 
               'Set-AzNetworkManagerSecurityAdminRule', 
               'Get-AzNetworkManagerActiveConnectivityConfiguration', 
               'Get-AzNetworkManagerActiveSecurityAdminRule', 
               'Get-AzNetworkManagerEffectiveConnectivityConfiguration', 
               'Get-AzNetworkManagerEffectiveSecurityAdminRule', 
               'Deploy-AzNetworkManagerCommit', 
               'Get-AzNetworkManagerDeploymentStatus', 
               'New-AzNetworkManagerAddressPrefixItem', 
               'New-AzNetworkManagerScope', 
               'New-AzNetworkManagerSecurityGroupItem', 'New-AzNetworkManagerHub', 
               'New-AzNetworkManagerConnectivityGroupItem', 
               'New-AzNetworkManagerStaticMember', 
               'Get-AzNetworkManagerStaticMember', 
               'Remove-AzNetworkManagerStaticMember', 
               'New-AzNetworkManagerSubscriptionConnection', 
               'Get-AzNetworkManagerSubscriptionConnection', 
               'Remove-AzNetworkManagerSubscriptionConnection', 
               'Set-AzNetworkManagerSubscriptionConnection', 
               'New-AzNetworkManagerScopeConnection', 
               'Get-AzNetworkManagerScopeConnection', 
               'Remove-AzNetworkManagerScopeConnection', 
               'Set-AzNetworkManagerScopeConnection', 
               'New-AzNetworkManagerManagementGroupConnection', 
               'Get-AzNetworkManagerManagementGroupConnection', 
               'Remove-AzNetworkManagerManagementGroupConnection', 
               'Set-AzNetworkManagerManagementGroupConnection', 
               'Get-AzFirewallLearnedIpPrefix'

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'List-AzApplicationGatewayAvailableWafRuleSets', 
               'List-AzApplicationGatewayAvailableSslOptions', 
               'List-AzApplicationGatewaySslPredefinedPolicy', 
               'List-AzApplicationGatewayAvailableServerVariableAndHeader', 
               'Add-AzApplicationGatewayBackendHttpSettings', 
               'Get-AzApplicationGatewayBackendHttpSettings', 
               'New-AzApplicationGatewayBackendHttpSettings', 
               'Remove-AzApplicationGatewayBackendHttpSettings', 
               'Set-AzApplicationGatewayBackendHttpSettings', 
               'Get-AzExpressRouteCircuitStats', 
               'Get-AzApplicationGatewayAvailableWafRuleSets', 
               'Get-AzApplicationGatewayAvailableSslOptions', 
               'Get-AzInterfaceEndpoint', 
               'New-AzFirewallThreatIntelWhitelistObject'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Azure','ResourceManager','ARM','Network','VirtualNetwork'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/azps-license'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Azure/azure-powershell'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '* Added optional parameters ''CustomBlockResponseStatusCode'' and ''CustomBlockResponseBody'' parameter to ''AzApplicationGatewayFirewallPolicySettings''
* Added a new cmdlet to get the application gateway waf manifest and rules
    - ''Get-AzApplicationGatewayWafDynamicManifest'''

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIInygYJKoZIhvcNAQcCoIInuzCCJ7cCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCBJI1LRUNX0BVk1
# OLRSydc1LAzjlZKOgDZDS9bpC7UO6aCCDYEwggX/MIID56ADAgECAhMzAAACzI61
# lqa90clOAAAAAALMMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjIwNTEyMjA0NjAxWhcNMjMwNTExMjA0NjAxWjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQCiTbHs68bADvNud97NzcdP0zh0mRr4VpDv68KobjQFybVAuVgiINf9aG2zQtWK
# No6+2X2Ix65KGcBXuZyEi0oBUAAGnIe5O5q/Y0Ij0WwDyMWaVad2Te4r1Eic3HWH
# UfiiNjF0ETHKg3qa7DCyUqwsR9q5SaXuHlYCwM+m59Nl3jKnYnKLLfzhl13wImV9
# DF8N76ANkRyK6BYoc9I6hHF2MCTQYWbQ4fXgzKhgzj4zeabWgfu+ZJCiFLkogvc0
# RVb0x3DtyxMbl/3e45Eu+sn/x6EVwbJZVvtQYcmdGF1yAYht+JnNmWwAxL8MgHMz
# xEcoY1Q1JtstiY3+u3ulGMvhAgMBAAGjggF+MIIBejAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQUiLhHjTKWzIqVIp+sM2rOHH11rfQw
# UAYDVR0RBEkwR6RFMEMxKTAnBgNVBAsTIE1pY3Jvc29mdCBPcGVyYXRpb25zIFB1
# ZXJ0byBSaWNvMRYwFAYDVQQFEw0yMzAwMTIrNDcwNTI5MB8GA1UdIwQYMBaAFEhu
# ZOVQBdOCqhc3NyK1bajKdQKVMFQGA1UdHwRNMEswSaBHoEWGQ2h0dHA6Ly93d3cu
# bWljcm9zb2Z0LmNvbS9wa2lvcHMvY3JsL01pY0NvZFNpZ1BDQTIwMTFfMjAxMS0w
# Ny0wOC5jcmwwYQYIKwYBBQUHAQEEVTBTMFEGCCsGAQUFBzAChkVodHRwOi8vd3d3
# Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRzL01pY0NvZFNpZ1BDQTIwMTFfMjAx
# MS0wNy0wOC5jcnQwDAYDVR0TAQH/BAIwADANBgkqhkiG9w0BAQsFAAOCAgEAeA8D
# sOAHS53MTIHYu8bbXrO6yQtRD6JfyMWeXaLu3Nc8PDnFc1efYq/F3MGx/aiwNbcs
# J2MU7BKNWTP5JQVBA2GNIeR3mScXqnOsv1XqXPvZeISDVWLaBQzceItdIwgo6B13
# vxlkkSYMvB0Dr3Yw7/W9U4Wk5K/RDOnIGvmKqKi3AwyxlV1mpefy729FKaWT7edB
# d3I4+hldMY8sdfDPjWRtJzjMjXZs41OUOwtHccPazjjC7KndzvZHx/0VWL8n0NT/
# 404vftnXKifMZkS4p2sB3oK+6kCcsyWsgS/3eYGw1Fe4MOnin1RhgrW1rHPODJTG
# AUOmW4wc3Q6KKr2zve7sMDZe9tfylonPwhk971rX8qGw6LkrGFv31IJeJSe/aUbG
# dUDPkbrABbVvPElgoj5eP3REqx5jdfkQw7tOdWkhn0jDUh2uQen9Atj3RkJyHuR0
# GUsJVMWFJdkIO/gFwzoOGlHNsmxvpANV86/1qgb1oZXdrURpzJp53MsDaBY/pxOc
# J0Cvg6uWs3kQWgKk5aBzvsX95BzdItHTpVMtVPW4q41XEvbFmUP1n6oL5rdNdrTM
# j/HXMRk1KCksax1Vxo3qv+13cCsZAaQNaIAvt5LvkshZkDZIP//0Hnq7NnWeYR3z
# 4oFiw9N2n3bb9baQWuWPswG0Dq9YT9kb+Cs4qIIwggd6MIIFYqADAgECAgphDpDS
# AAAAAAADMA0GCSqGSIb3DQEBCwUAMIGIMQswCQYDVQQGEwJVUzETMBEGA1UECBMK
# V2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0
# IENvcnBvcmF0aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0aWZpY2F0
# ZSBBdXRob3JpdHkgMjAxMTAeFw0xMTA3MDgyMDU5MDlaFw0yNjA3MDgyMTA5MDla
# MH4xCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdS
# ZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMT
# H01pY3Jvc29mdCBDb2RlIFNpZ25pbmcgUENBIDIwMTEwggIiMA0GCSqGSIb3DQEB
# AQUAA4ICDwAwggIKAoICAQCr8PpyEBwurdhuqoIQTTS68rZYIZ9CGypr6VpQqrgG
# OBoESbp/wwwe3TdrxhLYC/A4wpkGsMg51QEUMULTiQ15ZId+lGAkbK+eSZzpaF7S
# 35tTsgosw6/ZqSuuegmv15ZZymAaBelmdugyUiYSL+erCFDPs0S3XdjELgN1q2jz
# y23zOlyhFvRGuuA4ZKxuZDV4pqBjDy3TQJP4494HDdVceaVJKecNvqATd76UPe/7
# 4ytaEB9NViiienLgEjq3SV7Y7e1DkYPZe7J7hhvZPrGMXeiJT4Qa8qEvWeSQOy2u
# M1jFtz7+MtOzAz2xsq+SOH7SnYAs9U5WkSE1JcM5bmR/U7qcD60ZI4TL9LoDho33
# X/DQUr+MlIe8wCF0JV8YKLbMJyg4JZg5SjbPfLGSrhwjp6lm7GEfauEoSZ1fiOIl
# XdMhSz5SxLVXPyQD8NF6Wy/VI+NwXQ9RRnez+ADhvKwCgl/bwBWzvRvUVUvnOaEP
# 6SNJvBi4RHxF5MHDcnrgcuck379GmcXvwhxX24ON7E1JMKerjt/sW5+v/N2wZuLB
# l4F77dbtS+dJKacTKKanfWeA5opieF+yL4TXV5xcv3coKPHtbcMojyyPQDdPweGF
# RInECUzF1KVDL3SV9274eCBYLBNdYJWaPk8zhNqwiBfenk70lrC8RqBsmNLg1oiM
# CwIDAQABo4IB7TCCAekwEAYJKwYBBAGCNxUBBAMCAQAwHQYDVR0OBBYEFEhuZOVQ
# BdOCqhc3NyK1bajKdQKVMBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIAQwBBMAsGA1Ud
# DwQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB8GA1UdIwQYMBaAFHItOgIxkEO5FAVO
# 4eqnxzHRI4k0MFoGA1UdHwRTMFEwT6BNoEuGSWh0dHA6Ly9jcmwubWljcm9zb2Z0
# LmNvbS9wa2kvY3JsL3Byb2R1Y3RzL01pY1Jvb0NlckF1dDIwMTFfMjAxMV8wM18y
# Mi5jcmwwXgYIKwYBBQUHAQEEUjBQME4GCCsGAQUFBzAChkJodHRwOi8vd3d3Lm1p
# Y3Jvc29mdC5jb20vcGtpL2NlcnRzL01pY1Jvb0NlckF1dDIwMTFfMjAxMV8wM18y
# Mi5jcnQwgZ8GA1UdIASBlzCBlDCBkQYJKwYBBAGCNy4DMIGDMD8GCCsGAQUFBwIB
# FjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2RvY3MvcHJpbWFyeWNw
# cy5odG0wQAYIKwYBBQUHAgIwNB4yIB0ATABlAGcAYQBsAF8AcABvAGwAaQBjAHkA
# XwBzAHQAYQB0AGUAbQBlAG4AdAAuIB0wDQYJKoZIhvcNAQELBQADggIBAGfyhqWY
# 4FR5Gi7T2HRnIpsLlhHhY5KZQpZ90nkMkMFlXy4sPvjDctFtg/6+P+gKyju/R6mj
# 82nbY78iNaWXXWWEkH2LRlBV2AySfNIaSxzzPEKLUtCw/WvjPgcuKZvmPRul1LUd
# d5Q54ulkyUQ9eHoj8xN9ppB0g430yyYCRirCihC7pKkFDJvtaPpoLpWgKj8qa1hJ
# Yx8JaW5amJbkg/TAj/NGK978O9C9Ne9uJa7lryft0N3zDq+ZKJeYTQ49C/IIidYf
# wzIY4vDFLc5bnrRJOQrGCsLGra7lstnbFYhRRVg4MnEnGn+x9Cf43iw6IGmYslmJ
# aG5vp7d0w0AFBqYBKig+gj8TTWYLwLNN9eGPfxxvFX1Fp3blQCplo8NdUmKGwx1j
# NpeG39rz+PIWoZon4c2ll9DuXWNB41sHnIc+BncG0QaxdR8UvmFhtfDcxhsEvt9B
# xw4o7t5lL+yX9qFcltgA1qFGvVnzl6UJS0gQmYAf0AApxbGbpT9Fdx41xtKiop96
# eiL6SJUfq/tHI4D1nvi/a7dLl+LrdXga7Oo3mXkYS//WsyNodeav+vyL6wuA6mk7
# r/ww7QRMjt/fdW1jkT3RnVZOT7+AVyKheBEyIXrvQQqxP/uozKRdwaGIm1dxVk5I
# RcBCyZt2WwqASGv9eZ/BvW1taslScxMNelDNMYIZnzCCGZsCAQEwgZUwfjELMAkG
# A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQx
# HjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEoMCYGA1UEAxMfTWljcm9z
# b2Z0IENvZGUgU2lnbmluZyBQQ0EgMjAxMQITMwAAAsyOtZamvdHJTgAAAAACzDAN
# BglghkgBZQMEAgEFAKCBrjAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgor
# BgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAvBgkqhkiG9w0BCQQxIgQgLY2vX4I4
# um4v+m+gjoX9llvYgposTc9mBXxjhWspoUwwQgYKKwYBBAGCNwIBDDE0MDKgFIAS
# AE0AaQBjAHIAbwBzAG8AZgB0oRqAGGh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbTAN
# BgkqhkiG9w0BAQEFAASCAQB+m5blodPV8coOYcAMxTs/W0mMUucD9CgLTBjKNDxG
# R/Ku0RNIak0TSyoQdaiU31cMHDPon5sGgyJBqLqffUY/jt7R8wlo87TOtZQdAm/E
# aZcLHTDxx87k5dqWE32jMLJ0+G2cFYIRV5ddRp2gWQd8KY6mUZzVFVTX0hMKpse4
# wzYse67MmWu1PWVKlsIkyl9TAM/8kej0wVHGMvScl+MYOKMEYg/ZrfO8E5a1cXzP
# bSz/ug3mZZQxLaJQaBSuwxRPa53BBdKEEf9rUzoZnDzRFK2mx96Va1qQqtSWBc+r
# k5z0/f0xWQzM5LqsM/p7/lEWKPFUw0QZE10NgqqJ1VmuoYIXKTCCFyUGCisGAQQB
# gjcDAwExghcVMIIXEQYJKoZIhvcNAQcCoIIXAjCCFv4CAQMxDzANBglghkgBZQME
# AgEFADCCAVkGCyqGSIb3DQEJEAEEoIIBSASCAUQwggFAAgEBBgorBgEEAYRZCgMB
# MDEwDQYJYIZIAWUDBAIBBQAEIO3rWHwcZlTTg7YexSiNIk5Hk+BB8P1+F14hoJ79
# BX2MAgZjdOa2g+EYEzIwMjIxMjAxMTEyNjIwLjIwMlowBIACAfSggdikgdUwgdIx
# CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
# b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xLTArBgNVBAsTJE1p
# Y3Jvc29mdCBJcmVsYW5kIE9wZXJhdGlvbnMgTGltaXRlZDEmMCQGA1UECxMdVGhh
# bGVzIFRTUyBFU046RDA4Mi00QkZELUVFQkExJTAjBgNVBAMTHE1pY3Jvc29mdCBU
# aW1lLVN0YW1wIFNlcnZpY2WgghF4MIIHJzCCBQ+gAwIBAgITMwAAAbofPxn3wXW9
# fAABAAABujANBgkqhkiG9w0BAQsFADB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMK
# V2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0
# IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0Eg
# MjAxMDAeFw0yMjA5MjAyMDIyMTlaFw0yMzEyMTQyMDIyMTlaMIHSMQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQg
# SXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJjAkBgNVBAsTHVRoYWxlcyBUU1Mg
# RVNOOkQwODItNEJGRC1FRUJBMSUwIwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFt
# cCBTZXJ2aWNlMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAiE4VgzOS
# NYAT1RWdcX2FEa/TEFHFz4jke7eHFUVfIre7fzG6wRvSkuTCOAa0OxostuuUzGpf
# e0Vv/cGAQ8QLcvTBfvqAPzMe37CIFXmarkFainb2pGuAwkooI9ylCdKOz0H/hcwU
# W+ul0+JxkO/jcUuDP18eoyrQskPDkkAcYNLfRMJj04Xjc/h3jhn2UTsJpVLakkwX
# cvjncxcHnJgr8oNuKWERE/WPGfbKX60YJGC4gCwwbSh46FdrDy5IY6FLoAJIdv55
# uLTTfwwUfKhM2Ep/5Jijg6lJjfE/j6zAEFMoOhg/XAf4J/EbqH1/KYElA9Blqp+X
# SuKIMuOYO6dC0fUYPrgCKvmT0l3CGrnAuZJZePIVUv4gN86l2LEnp/mj4yETofi3
# fXD6mvKAeZ3ZQdDrntQbHoU27PAL5KkAeZXvoxlhpzi4CFOBo/js/Z55LWhyS/KG
# X3Jr70nM98yS6DfF6/MUANaItEyvTroQxXurclJECycJL0ZDTwLgUo9tKHw48zfc
# ueDR9/EA2ccABf8MTtwdzHuX2NpXcByaSPuiqKvgSHa7ljHCJpMTftdoy6ZfYRLc
# 8nk0Fperth0snDJIP5T2mT+2Xh1DW38R6ju4NOWI7JCQPwjvjGlUHRPfX/rsod+Q
# GQVW/LrDJ7bVX70gLy5IP75GAPdHC03aQT8CAwEAAaOCAUkwggFFMB0GA1UdDgQW
# BBSKYubxAx4lrbmP0xZ5psjYdK9k5TAfBgNVHSMEGDAWgBSfpxVdAF5iXYP05dJl
# pxtTNRnpcjBfBgNVHR8EWDBWMFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIwMjAx
# MCgxKS5jcmwwbAYIKwYBBQUHAQEEYDBeMFwGCCsGAQUFBzAChlBodHRwOi8vd3d3
# Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMFRpbWUtU3Rh
# bXAlMjBQQ0ElMjAyMDEwKDEpLmNydDAMBgNVHRMBAf8EAjAAMBYGA1UdJQEB/wQM
# MAoGCCsGAQUFBwMIMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAgEA
# X8jxTqFtmG8Nyf3qdnq2RtISNc+8pnrCuhpdyCy0SGmBp4TCV4u49ccvMRa24m5j
# Ph6yGaFeoWvj2VsBxflI3n9wSw/TF0VrJvtTk/3gll3ceMW+lZE2g0GEXdIMzQDf
# ywjYf6GOEH9V9fVdxmJ6LVE48DIIdwGAcvJCsS7qadvceFsh2vyHRNrtYXKUaEtI
# VbrCbMq6w/po6WacZJpzk0x+VrqVG9Ngd3byttsKB9KbVGFOChmP5bwNMq2IQzC5
# scneYg8qajzG0khZc+derpcqCV2svlzKcsxf/RZfrk65ZsdXkZMQt19a8ZXcNpms
# c9RD9Q/fUp6pvbGNUJvfQtXCBuMi9hLvs3V0BGQ3wX/2knWA7gi9lYzDIyUooUai
# M7V/XBuNJZwD/nu2xz63ZuWsxaBI0eDMOvTWNs9K6lGPLce31lmzjE3TZ6Jfd4bb
# 3s2u0LqXhz+DOfbR6qipbH+4dbGZOAHQXmiwG5Mc57vsPIQDS6ECsaWAo/3WOCGC
# 385UegfrmDRCoK2Bn7fqacISDog6EWgWsJzR8kUZWZvX7XuAR74dEwzuMGTg7Ton
# 4iigWsjd7c8mM+tBqej8zITeH7MC4FYYwNFxSU0oINTt0ada8fddbAusIIhzP7cb
# BFQywuwN09bY5W/u/V4QmIxIhnY/4zsvbRDxrOdTg4AwggdxMIIFWaADAgECAhMz
# AAAAFcXna54Cm0mZAAAAAAAVMA0GCSqGSIb3DQEBCwUAMIGIMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQgUm9v
# dCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkgMjAxMDAeFw0yMTA5MzAxODIyMjVaFw0z
# MDA5MzAxODMyMjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9u
# MRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
# b24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMIICIjAN
# BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA5OGmTOe0ciELeaLL1yR5vQ7VgtP9
# 7pwHB9KpbE51yMo1V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5KWv64NmeFRiMM
# tY0Tz3cywBAY6GB9alKDRLemjkZrBxTzxXb1hlDcwUTIcVxRMTegCjhuje3XD9gm
# U3w5YQJ6xKr9cmmvHaus9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl3GoPz130
# /o5Tz9bshVZN7928jaTjkY+yOSxRnOlwaQ3KNi1wjjHINSi947SHJMPgyY9+tVSP
# 3PoFVZhtaDuaRr3tpK56KTesy+uDRedGbsoy1cCGMFxPLOJiss254o2I5JasAUq7
# vnGpF1tnYN74kpEeHT39IM9zfUGaRnXNxF803RKJ1v2lIH1+/NmeRd+2ci/bfV+A
# utuqfjbsNkz2K26oElHovwUDo9Fzpk03dJQcNIIP8BDyt0cY7afomXw/TNuvXsLz
# 1dhzPUNOwTM5TI4CvEJoLhDqhFFG4tG9ahhaYQFzymeiXtcodgLiMxhy16cg8ML6
# EgrXY28MyTZki1ugpoMhXV8wdJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y1BzFa/Zc
# UlFdEtsluq9QBXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94q0W29R6HXtqPnhZy
# acaue7e3PmriLq0CAwEAAaOCAd0wggHZMBIGCSsGAQQBgjcVAQQFAgMBAAEwIwYJ
# KwYBBAGCNxUCBBYEFCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1UdDgQWBBSfpxVd
# AF5iXYP05dJlpxtTNRnpcjBcBgNVHSAEVTBTMFEGDCsGAQQBgjdMg30BATBBMD8G
# CCsGAQUFBwIBFjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL0RvY3Mv
# UmVwb3NpdG9yeS5odG0wEwYDVR0lBAwwCgYIKwYBBQUHAwgwGQYJKwYBBAGCNxQC
# BAweCgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYD
# VR0jBBgwFoAU1fZWy4/oolxiaNE9lJBb186aGMQwVgYDVR0fBE8wTTBLoEmgR4ZF
# aHR0cDovL2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9v
# Q2VyQXV0XzIwMTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEBBE4wTDBKBggrBgEFBQcw
# AoY+aHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNSb29DZXJB
# dXRfMjAxMC0wNi0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIBAJ1VffwqreEsH2cB
# MSRb4Z5yS/ypb+pcFLY+TkdkeLEGk5c9MTO1OdfCcTY/2mRsfNB1OW27DzHkwo/7
# bNGhlBgi7ulmZzpTTd2YurYeeNg2LpypglYAA7AFvonoaeC6Ce5732pvvinLbtg/
# SHUB2RjebYIM9W0jVOR4U3UkV7ndn/OOPcbzaN9l9qRWqveVtihVJ9AkvUCgvxm2
# EhIRXT0n4ECWOKz3+SmJw7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWKNsIdw2Fz
# Lixre24/LAl4FOmRsqlb30mjdAy87JGA0j3mSj5mO0+7hvoyGtmW9I/2kQH2zsZ0
# /fZMcm8Qq3UwxTSwethQ/gpY3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+c23Kjgm9
# swFXSVRk2XPXfx5bRAGOWhmRaw2fpCjcZxkoJLo4S5pu+yFUa2pFEUep8beuyOiJ
# Xk+d0tBMdrVXVAmxaQFEfnyhYWxz/gq77EFmPWn9y8FBSX5+k77L+DvktxW/tM4+
# pTFRhLy/AsGConsXHRWJjXD+57XQKBqJC4822rpM+Zv/Cuk0+CQ1ZyvgDbjmjJnW
# 4SLq8CdCPSWU5nR0W2rRnj7tfqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/2XBjU02N
# 7oJtpQUQwXEGahC0HVUzWLOhcGbyoYIC1DCCAj0CAQEwggEAoYHYpIHVMIHSMQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNy
# b3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJjAkBgNVBAsTHVRoYWxl
# cyBUU1MgRVNOOkQwODItNEJGRC1FRUJBMSUwIwYDVQQDExxNaWNyb3NvZnQgVGlt
# ZS1TdGFtcCBTZXJ2aWNloiMKAQEwBwYFKw4DAhoDFQB2o0d7XXeAInztpkgZrlAF
# SojC8qCBgzCBgKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9u
# MRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
# b24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMA0GCSqG
# SIb3DQEBBQUAAgUA5zKCpzAiGA8yMDIyMTIwMTA5MzIyM1oYDzIwMjIxMjAyMDkz
# MjIzWjB0MDoGCisGAQQBhFkKBAExLDAqMAoCBQDnMoKnAgEAMAcCAQACAg1pMAcC
# AQACAhE4MAoCBQDnM9QnAgEAMDYGCisGAQQBhFkKBAIxKDAmMAwGCisGAQQBhFkK
# AwKgCjAIAgEAAgMHoSChCjAIAgEAAgMBhqAwDQYJKoZIhvcNAQEFBQADgYEAI9VZ
# ijcsPscCucB35Tb3AAvpZUTwJryfKDl3UbUaFyoikeYNA3HD2WkLsmFhFOCoMfP0
# mT0WgTPvTNaEFdXVX8hQUqaPwsx670XFGP5fMS1IV4VIkNI0C4uCPxZ6D0gQR0kW
# Vmtcz4UnLGHni4bOh+KdOMYGDJtZlLEyi/+RFI4xggQNMIIECQIBATCBkzB8MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNy
# b3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAITMwAAAbofPxn3wXW9fAABAAABujAN
# BglghkgBZQMEAgEFAKCCAUowGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEEMC8G
# CSqGSIb3DQEJBDEiBCB6PmXeiAv1oMUl0N7esE+gZ5d1dxQbuLpISz6nhwZjcTCB
# +gYLKoZIhvcNAQkQAi8xgeowgecwgeQwgb0EIClVvTwzbnD61gZayaUa2nWDLWc9
# ypZ+qAwXeeVZhXMFMIGYMIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldh
# c2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBD
# b3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIw
# MTACEzMAAAG6Hz8Z98F1vXwAAQAAAbowIgQgrjSpFN94ftRROrUj6SeaDmysst9S
# cq8mAdL1hi2k+DcwDQYJKoZIhvcNAQELBQAEggIAFzYiXa66LnBjq0RmY8bRxK+P
# bJbhCwVxUlIZlBSlI5abof+QTXvG7SkJj0Vsb0fx5KvrXhdKix+jxjK/ZOUUBV6f
# CF7nLu09eNmdQE6X6qjKR95oxCIkPrdy1J3zUzxmuhRUywGfl6ne85EpfBbIYYaH
# co+4AyjTuuiNFbx9BHQCEcPqp8IlWCKGsqzUfvbuUxsVhFOGuDIJDCzZzdoGBCIe
# 1FZT0X4iMoRnjWraEoC2bmL2ilDptlyHnAGXL9F87BlsLxX2v1FXPmq8IXJmIfsa
# yXFj4B29gA+SdhrG1A4hBjMo4V1O6aZvaEW7Bx6siOKhPl+K7Q01zkIVRSPOMpO1
# M577DHfivN+0mYSJITWoikF4Ji9NJKjITqfcV12aR41ETQmZr2mmlHcUxlna1xJ0
# 7deUJK4AW3x3PC4C5HCe/wf8cPn0C3FzRVjtzRCb2fiU7hLCOscHIvgTOu4C5uu4
# mrysd4LwT9nD97CjZbZ1+pEXWe9rw57qKGKXAdxdSgiHn9zu7E0v+lY2oZ70wHjV
# //s9FO7Iia91Hp6ZVG0TeNAN85givQ/TI9HDQ627iAJQETnTnVy8ZFvohGsJq8z1
# NiiMdUdwNyJ224umwD5QffIEG/4sru51Rjh3m2y544nzes7rXL2A81y3IRiZCdYp
# ecyvzlL0X7oNVjvaheU=
# SIG # End signature block
